# Generated by Django 5.1.6 on 2025-04-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='post_type',
            field=models.CharField(choices=[('general', 'General'), ('review', 'Review'), ('announcement', 'Announcement')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
