# Generated by Django 5.1.6 on 2025-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='request',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='request',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_seeker',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=255),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
