# Generated by Django 5.1.6 on 2025-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_application'),
        ('users', '0003_user_company_user_role_alter_employer_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'job_seeker')},
        ),
    ]
