# Generated by Django 5.0.2 on 2025-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_favoritevacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, help_text='Требования к кандидату'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type',
            field=models.CharField(choices=[('FULL', 'Full-time'), ('PART', 'Part-time')], default='FULL', max_length=20),
        ),
    ]
