# Generated by Django 5.1.6 on 2025-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_founded_year_company_industry_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='work_type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('KZT', 'KZT'), ('USD', 'USD'), ('EUR', 'EUR')], default='KZT', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('CONTRACT', 'Contract')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Middle'), ('SENIOR', 'Senior')], default='MID', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, default='Remote', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FavoriteVacancy',
        ),
    ]
