# Generated by Django 5.1.6 on 2025-03-31 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Название резюме, например 'Backend Developer'.", max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Краткое описание или summary.')),
                ('file', models.FileField(blank=True, help_text='PDF', null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.jobseeker')),
            ],
        ),
    ]
