# Generated by Django 5.1.6 on 2025-04-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, help_text='PDF файл', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_language',
            field=models.CharField(choices=[('KAZAKH', 'Kazakh'), ('RUSSIAN', 'Russian'), ('ENGLISH', 'English')], default='ENGLISH', max_length=10),
        ),
    ]
