# Generated by Django 5.0.2 on 2025-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_user_role_alter_employer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='position',
            field=models.CharField(blank=True, help_text='Должность в компании', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, help_text='О себе'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(blank=True, help_text='Город проживания', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, help_text='Навыки, например: Python, SQL, Django', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
