# Generated by Django 5.1.6 on 2025-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employer_position_jobseeker_bio_jobseeker_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
