# Generated by Django 5.1.6 on 2025-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.TextField(blank=True, help_text='Сертификаты'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.TextField(blank=True, help_text='Образование'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.TextField(blank=True, help_text='Опыт работы'),
        ),
    ]
