# Generated by Django 5.0.2 on 2025-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_by_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
